# Generated by Django 6.1.1 on 2026-10-07 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeniorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('area', models.CharField(max_length=100, verbose_name='住んでいる地域')),
                ('introduction', models.TextField(blank=True, verbose_name='自己紹介')),
                ('needs', models.TextField(blank=True, verbose_name='頼みたいこと')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('university', models.CharField(max_length=100, verbose_name='大学・学年')),
                ('introduction', models.TextField(blank=True, verbose_name='自己紹介')),
                ('skills', models.TextField(blank=True, verbose_name='できること')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
