# Generated by Django 6.1.2 on 2026-10-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='依頼内容')),
                ('area', models.CharField(max_length=50, verbose_name='地域')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('start_at', models.DateTimeField(verbose_name='希望開始')),
                ('end_at', models.DateTimeField(verbose_name='希望終了')),
                ('status', models.CharField(choices=[('open', '募集中'), ('accepted', '引き受け済み'), ('done', '完了')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
